/* Warning, this file is autogenerated by cbindgen. Don't modify this manually. */

#include <stdarg.h>
#include <stdbool.h>
#include <stdint.h>
#include <stdlib.h>
#include <zephyr/drivers/gpio.h>

/**
 * Toggles LEDs, i.e., turns them on & off based on the given configuration (frequencies & delays).
 * Each LED will blink in its given frequency and will start to blink after given delay.
 */
void toggle_leds(const struct gpio_dt_spec *led1, const struct gpio_dt_spec *led2, const struct gpio_dt_spec *led3);

/**
 * Displays text on screen as given by configuration.
 */
void display_text(void);
